"""add meet table

Revision ID: 36182516dc8f
Revises: 7235956a37e6
Create Date: 2025-04-23 22:18:45.000592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36182516dc8f'
down_revision = '7235956a37e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meet')
    # ### end Alembic commands ###
