"""delete colom image on student table

Revision ID: 7235956a37e6
Revises: 7ccdf6438170
Create Date: 2025-04-23 21:44:59.350365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7235956a37e6'
down_revision = '7ccdf6438170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', mysql.VARCHAR(length=225), nullable=False))

    # ### end Alembic commands ###
