"""add relationship on student table

Revision ID: 7ccdf6438170
Revises: dfce58ad44ea
Create Date: 2025-04-23 21:31:49.959309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccdf6438170'
down_revision = 'dfce58ad44ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('images', sa.String(length=225), nullable=False))
        batch_op.create_foreign_key(None, 'grade', ['grade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('images')
        batch_op.drop_column('grade_id')

    # ### end Alembic commands ###
