"""add modul class, attendance, student, and user

Revision ID: 82339f36afed
Revises: bb14c7cfeace
Create Date: 2025-03-27 10:58:44.074087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82339f36afed'
down_revision = 'bb14c7cfeace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nis', sa.String(length=100), nullable=False),
    sa.Column('class_id', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=225), nullable=False),
    sa.Column('face_encoding', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nis')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('S', 'H', 'I', 'A', name='status'), nullable=False),
    sa.Column('photo_url', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('M', 'F'),
               type_=sa.Enum('A', 'G', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('A', 'G', name='role'),
               type_=mysql.ENUM('M', 'F'),
               existing_nullable=False)

    op.drop_table('attendance')
    op.drop_table('student')
    op.drop_table('class')
    # ### end Alembic commands ###
